### ISSUE TITLE
No Issue - just wanted to leave a "hello" ;-)

### ISSUE THREAD

**Issue by hobbyquaker** [forty2/hap-client-tool#2]
Hi Zach, 
awesome work! Just wanted to point you on another usecase for the hap-client(-tool):
I just started to implement test-automation for https://github.com/hobbyquaker/homekit2mqtt and with your hap-client I have to possibility to do real system tests and get the test coverage nearer to 100% ;-) 
Thanks and keep up the good work,
Sebastian

**Comment by forty2** [comment]
Hi Sebastian,

Thanks for the heads up -- I always like hearing about it when people come up with uses I hadn't thought of.  Hopefully it works well for you, but if not, let me know how I can help!  Now that I've got my notifications sorted out, it shouldn't take so long for me to notice bug activity next time :-)
